baseURL = "https://example.com/"
languageCode = "en-us"
title = "Hugo-HT"
theme = "hugo-ht"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
footnotereturnlinkcontents = "↩"

[permalinks]
cn = "/cn/:year/:month/:day/:slug/"
en = "/en/:year/:month/:day/:slug/"

[[menu.en]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.en]]
    name = "About"
    url = "/en/about/"
    weight = 2
[[menu.en]]
    name = "Posts"
    url = "/en/posts/"
    weight = 3
[[menu.en]]
    name = "中文"
    url = "/cn/posts/"
    weight = 4
[[menu.cn]]
    name = "关于"
    url = "/cn/about/"
    weight = 1
[[menu.cn]]
    name = "日志"
    url = "/cn/posts/"
    weight = 2
[[menu.cn]]
    name = "English"
    url = "/"
    weight = 3

[params]
    description = "Peronal website of Your Name"
    homeText = "You just need a Hugo blog from scratch"
    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs" 
    MathJaxVersion = "2.7.5"
    favicon = "media/hugo-logo.png"
    GithubEdit = "https://github.com/USERNAME/REPONAME/edit/master/content/"
    copyright = "&copy;"
    copyrightYear = "2021"
    SiteUpdateText = "site last updated on"

[params.logo]
  url = "hugo-logo.png"
  width = 50.0
  height = 50.0
  alt = "Hugo-ht"

[params.author]
  en = "Your Name"
  cn = "你的名字"

[params.lang]

  [params.lang.edit]
    en = "Suggest an edit of this page"
    cn = "编辑本页"

  [params.lang.lastupdate]
    en = "Last modified on"
    cn = "最后一次修改于"

[markup]
 defaultMarkdownHandler = "goldmark"

  [markup.goldmark]

    [markup.goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = false
    strikethrough = true
    table = true
    taskList = true
    typographer = true

    [markup.goldmark.parser]
    attribute = true
    autoHeadingID = true

    [markup.goldmark.renderer]
    hardWraps = false
    unsafe = true
    xHTML = false
  
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "pygments"
    tabWidth = 4

  [markup.tableOfContents]
  endLevel = 3
  ordered = true
  startLevel = 2

[imaging]
quality = 100
      
